steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/youtube-transcript-api', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/youtube-transcript-api' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'youtube-transcript-api', 
           '--image', 'gcr.io/$PROJECT_ID/youtube-transcript-api',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated',
           '--set-env-vars', 'PYTHONUNBUFFERED=1']

# Images created by the build
images:
  - 'gcr.io/$PROJECT_ID/youtube-transcript-api'
